from mods import betterend
from core.provider import *
from core import constant
mod_id = "betterend"
run_list = []

run_list.append(DataPackProvider(mod_id))

sub_provider=PhaseProvider(mod_id)
run_list.append(sub_provider)

# 13
stage13 = SubPhaseTableBuilder(target=constant.STAGE_END.get_phase_id())
stage13.add_block(betterend.blocks.endstone_dust, 15)
stage13.add_block(betterend.blocks.end_mycelium, 15)
stage13.add_block(betterend.blocks.end_moss, 15)
stage13.add_block(betterend.blocks.chorus_nylium, 15)
stage13.add_block(betterend.blocks.cave_moss, 15)
stage13.add_block(betterend.blocks.crystal_moss, 15)
stage13.add_block(betterend.blocks.shadow_grass, 15)
stage13.add_block(betterend.blocks.pink_moss, 15)
stage13.add_block(betterend.blocks.amber_moss, 15)
stage13.add_block(betterend.blocks.jungle_moss, 15)
stage13.add_block(betterend.blocks.sangnum, 15)
stage13.add_block(betterend.blocks.rutiscus, 15)
stage13.add_block(betterend.blocks.amber_moss, 15)
stage13.add_block(betterend.blocks.pallidium_full, 5)
stage13.add_block(betterend.blocks.pallidium_heavy, 5)
stage13.add_block(betterend.blocks.pallidium_thin, 5)
stage13.add_block(betterend.blocks.pallidium_tiny, 5)
stage13.add_block(betterend.blocks.mossy_obsidian, 5)
stage13.add_block(betterend.blocks.flavolite, 5)
stage13.add_block(betterend.blocks.violecite, 5)
stage13.add_block(betterend.blocks.sulphuric_rock, 5)
stage13.add_block(betterend.blocks.virid_jadestone, 5)
stage13.add_block(betterend.blocks.azure_jadestone, 5)
stage13.add_block(betterend.blocks.sandy_jadestone, 5)
stage13.add_block(betterend.blocks.umbralith, 5)
stage13.add_block(betterend.blocks.brimstone, 2)
stage13.add_block(betterend.blocks.flavolite_runed, 2)
stage13.add_block(betterend.blocks.flavolite_runed_eternal, 1)
stage13.add_block(betterend.blocks.dense_snow, 2)
stage13.add_block(betterend.blocks.emerald_ice, 2)
stage13.add_block(betterend.blocks.mossy_glowshroom_log, 7)
stage13.add_block(betterend.blocks.end_lotus_log, 7)
stage13.add_block(betterend.blocks.pythadendron_log, 7)
stage13.add_block(betterend.blocks.lacugrove_log, 7)
stage13.add_block(betterend.blocks.dragon_tree_log, 7)
stage13.add_block(betterend.blocks.tenanea_log, 7)
stage13.add_block(betterend.blocks.helix_tree_log, 7)
stage13.add_block(betterend.blocks.umbrella_tree_log, 7)
stage13.add_block(betterend.blocks.umbrella_tree_cluster, 1)
stage13.add_block(betterend.blocks.umbrella_tree_cluster_empty, 1)
stage13.add_block(betterend.blocks.jellyshroom_cap_purple, 2)
stage13.add_block(betterend.blocks.jellyshroom_log, 7)
stage13.add_block(betterend.blocks.lucernia_log, 7)
stage13.add_block(betterend.blocks.amaranita_stem, 1)
stage13.add_block(betterend.blocks.amaranita_hyphae, 1)
stage13.add_block(betterend.blocks.amaranita_hymenophore, 12)
stage13.add_block(betterend.blocks.amaranita_lantern, 1)
stage13.add_block(betterend.blocks.amaranita_cap, 1)
stage13.add_block(betterend.blocks.neon_cactus_block, 3)
stage13.add_block(betterend.blocks.menger_sponge_wet, 2)
stage13.add_block(betterend.blocks.hydralux_petal_block, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_white, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_gray, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_light_gray, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_black, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_blue, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_lime, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_magenta, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_red, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_orange, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_purple, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_cyan, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_brown, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_green, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_yellow, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_pink, 1)
stage13.add_block(betterend.blocks.hydralux_petal_block_light_blue, 1)
stage13.add_block(betterend.blocks.filalux_lantern, 1)
stage13.add_block(betterend.blocks.ender_ore, 2)
stage13.add_block(betterend.blocks.amber_ore, 2)
stage13.add_block(betterend.blocks.thallasium_ore, 1)
stage13.add_block(betterend.blocks.aurora_crystal, 3)
stage13.add_block(betterend.blocks.smaragdant_crystal, 1)
stage13.add_block(betterend.blocks.budding_smaragdant_crystal, 1)
stage13.add_mob(betterend.entities.dragonfly, 2, 1)
stage13.add_mob(betterend.entities.end_slime, 2, 1)
stage13.add_mob(betterend.entities.end_fish, 2, 1)
stage13.add_mob(betterend.entities.shadow_walker, 2, 1)
stage13.add_mob(betterend.entities.cubozoa, 2, 1)
stage13.add_mob(betterend.entities.silk_moth, 2, 1)
sub_provider.add_phase("13", stage13)


loot_provider = ModifiedLootTableProvider(mod_id)
run_list.append(loot_provider)

# 13
loot13 = SingleLootTableBuilder()
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.end_lotus_seed, weight=6).add_count_function(2, 4))
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.lucernia_sapling, weight=6).add_count_function(2, 4))
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.dragon_tree_sapling, weight=6).add_count_function(2, 4))
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.pythadendron_sapling, weight=6).add_count_function(2, 4))
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.mossy_glowshroom_sapling, weight=6).add_count_function(2, 4))
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.helix_tree_sapling, weight=6).add_count_function(2, 4))
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.tenanea_sapling, weight=6).add_count_function(2, 4))
loot13.add_entry(SimplePoolEntryBuilder(betterend.blocks.umbrella_tree_sapling, weight=6).add_count_function(2, 4))
loot_provider.add_modified_loot(target=[constant.STAGE_END.stage_gift], table_id="13", table= loot13)
