from core.provider import *

mod_id = "ija-one-block"
run_list = []

aa = DataPackProvider(mod_id)
aa.get_datapack_name = (lambda: "ija-one-block")
run_list.append(aa)

loot_provider = LootTableProvider(mod_id)
loot_provider.get_datapack_name = (lambda: "ija-one-block")

run_list.append(loot_provider)

# 00-gift
loot_provider.add_loot(table_id="00-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:oak_sapling", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:oak_log", 1, 5, 6))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:torch", 1, 1, 1))
                       )

# 00
loot00 = SingleLootTableBuilder()
loot00.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 2))
loot00.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot00.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot00.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot_provider.add_loot(table_id="00", table=loot00)

# 01-gift
loot_provider.add_loot(table_id="01-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:apple", 1, 3, 5))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:oak_sapling", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:birch_sapling", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:grass_block", 1, 1, 1))
                       )

# 01
loot01 = SingleLootTableBuilder()
loot01.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot01.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot01.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot01.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot01.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot01.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot01.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot01.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot01.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot01.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot01.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="01", table=loot01)

# 02-gift
loot_provider.add_loot(table_id="02-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:spruce_sapling", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:map", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:coal", 1, 4, 6))
                       )

# 02-variety
loot02_variety = SingleLootTableBuilder()
loot02_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot02_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot_provider.add_loot(table_id="02-variety", table=loot02_variety)

# 02
loot02 = SingleLootTableBuilder()
loot02.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot02.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot02.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot02.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot02.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot02.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot02.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot_provider.add_loot(table_id="02", table=loot02)

# 03-gift
loot_provider.add_loot(table_id="03-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:bone_meal", 1, 3, 5))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:bone", 1, 4, 6))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:dark_oak_sapling", 1, 1, 2))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:ice", 1, 1, 1))
                       )

# 03-variety
loot03_variety = SingleLootTableBuilder()
loot03_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot03_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot_provider.add_loot(table_id="03-variety", table=loot03_variety)

# 03
loot03 = SingleLootTableBuilder()
loot03.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot03.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot03.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot03.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot03.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot03.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot03.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot03.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot03.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot03.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot03.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot_provider.add_loot(table_id="03", table=loot03)

# 04-gift
loot_provider.add_loot(table_id="04-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:salmon_bucket", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:cod_bucket", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:trident", 1, 1, 1))
                       )
# 04-variety
loot04_variety = SingleLootTableBuilder()
loot04_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot04_variety.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="04-variety", table=loot04_variety)

# 04
loot04 = SingleLootTableBuilder()
loot04.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot04.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot04.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot04.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot04.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot04.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot04.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="04", table=loot04)

# 05-gift
loot_provider.add_loot(table_id="05-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:jungle_sapling", 1, 1, 2))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:cocoa_beans", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:diamond", 1, 1, 2))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:bamboo", 1, 5, 7))
                       )

# 05-variety
loot05_variety = SingleLootTableBuilder()
loot05_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:lapis_lazuli", weight=6).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:jungle_sapling", weight=5).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:cocoa_beans", weight=5).add_count_function(1, 2))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:sugar_cane", weight=4).add_count_function(1, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:bamboo", weight=4).add_count_function(1, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:vine", weight=4).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:sugar", weight=3).add_count_function(2, 4))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=3).add_count_function(2, 4))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=3).add_count_function(1, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:paper", weight=3).add_count_function(2, 3))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot05_variety.add_entry(PoolEntryBuilder("minecraft:lead", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="05-variety", table=loot05_variety)

# 05
loot05 = SingleLootTableBuilder()
loot05.add_entry(PoolEntryBuilder("minecraft:lapis_lazuli", weight=6).add_count_function(2, 3))
loot05.add_entry(PoolEntryBuilder("minecraft:jungle_sapling", weight=5).add_count_function(1, 2))
loot05.add_entry(PoolEntryBuilder("minecraft:cocoa_beans", weight=5).add_count_function(1, 2))
loot05.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot05.add_entry(PoolEntryBuilder("minecraft:sugar_cane", weight=4).add_count_function(1, 3))
loot05.add_entry(PoolEntryBuilder("minecraft:bamboo", weight=4).add_count_function(1, 3))
loot05.add_entry(PoolEntryBuilder("minecraft:vine", weight=4).add_count_function(2, 3))
loot05.add_entry(PoolEntryBuilder("minecraft:sugar", weight=3).add_count_function(2, 4))
loot05.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=3).add_count_function(2, 4))
loot05.add_entry(PoolEntryBuilder("minecraft:bone", weight=3).add_count_function(1, 3))
loot05.add_entry(PoolEntryBuilder("minecraft:paper", weight=3).add_count_function(2, 3))
loot05.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot05.add_entry(PoolEntryBuilder("minecraft:lead", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="05", table=loot05)

# 06-gift
loot_provider.add_loot(table_id="06-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:cobweb", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:acacia_sapling", 1, 1, 2))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:experience_bottle", 1, 7, 10))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:emerald", 1, 6, 9))
                       )

# 06-variety
loot06_variety = SingleLootTableBuilder()
loot06_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:lapis_lazuli", weight=6).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:jungle_sapling", weight=5).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:cocoa_beans", weight=5).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:sugar_cane", weight=4).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bamboo", weight=4).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:vine", weight=4).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:sugar", weight=3).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=3).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=3).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:paper", weight=3).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:lead", weight=1).add_count_function(1, 1))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=8).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=7).add_count_function(2, 4))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:redstone", weight=5).add_count_function(2, 5))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:acacia_sapling", weight=5).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:emerald", weight=4).add_count_function(1, 2))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:cactus", weight=4).add_count_function(2, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=2).add_count_function(1, 3))
loot06_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=2).add_count_function(1, 3))
loot_provider.add_loot(table_id="06-variety", table=loot06_variety)

# 06
loot06 = SingleLootTableBuilder()
loot06.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=8).add_count_function(2, 4))
loot06.add_entry(PoolEntryBuilder("minecraft:bone", weight=7).add_count_function(2, 4))
loot06.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot06.add_entry(PoolEntryBuilder("minecraft:redstone", weight=5).add_count_function(2, 5))
loot06.add_entry(PoolEntryBuilder("minecraft:acacia_sapling", weight=5).add_count_function(1, 2))
loot06.add_entry(PoolEntryBuilder("minecraft:emerald", weight=4).add_count_function(1, 2))
loot06.add_entry(PoolEntryBuilder("minecraft:cactus", weight=4).add_count_function(2, 3))
loot06.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=2).add_count_function(1, 3))
loot06.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=2).add_count_function(1, 3))
loot_provider.add_loot(table_id="06", table=loot06)

# 07-gift
loot_provider.add_loot(table_id="07-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:lava_bucket", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:netherite_scrap", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:blaze_rod", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:fire_charge", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:magma_cream", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:blaze_powder", 1, 1, 2))
                       )

# 07-variety
loot07_variety = SingleLootTableBuilder()
loot07_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:lapis_lazuli", weight=6).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:jungle_sapling", weight=5).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:cocoa_beans", weight=5).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:sugar_cane", weight=4).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bamboo", weight=4).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:vine", weight=4).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:sugar", weight=3).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=3).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=3).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:paper", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:lead", weight=1).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=8).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=7).add_count_function(2, 4))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:redstone", weight=5).add_count_function(2, 5))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:acacia_sapling", weight=5).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:emerald", weight=4).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:cactus", weight=4).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=2).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=2).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:quartz", weight=5).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=4).add_count_function(1, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:twisting_vines", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:weeping_vines", weight=3).add_count_function(2, 3))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:lava_bucket", weight=3).add_count_function(1, 1))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:ghast_tear", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:blaze_rod", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:magma_cream", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:blaze_powder", weight=2).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:netherite_scrap", weight=1).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:nether_wart", weight=1).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:nether_sprouts", weight=1).add_count_function(1, 2))
loot07_variety.add_entry(PoolEntryBuilder("minecraft:wither_skeleton_skull", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="07-variety", table=loot07_variety)

# 07
loot07 = SingleLootTableBuilder()
loot07.add_entry(PoolEntryBuilder("minecraft:quartz", weight=5).add_count_function(2, 3))
loot07.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=4).add_count_function(1, 3))
loot07.add_entry(PoolEntryBuilder("minecraft:twisting_vines", weight=3).add_count_function(2, 3))
loot07.add_entry(PoolEntryBuilder("minecraft:weeping_vines", weight=3).add_count_function(2, 3))
loot07.add_entry(PoolEntryBuilder("minecraft:lava_bucket", weight=3).add_count_function(1, 1))
loot07.add_entry(PoolEntryBuilder("minecraft:ghast_tear", weight=2).add_count_function(1, 2))
loot07.add_entry(PoolEntryBuilder("minecraft:blaze_rod", weight=2).add_count_function(1, 2))
loot07.add_entry(PoolEntryBuilder("minecraft:magma_cream", weight=2).add_count_function(1, 2))
loot07.add_entry(PoolEntryBuilder("minecraft:blaze_powder", weight=2).add_count_function(1, 2))
loot07.add_entry(PoolEntryBuilder("minecraft:netherite_scrap", weight=1).add_count_function(1, 2))
loot07.add_entry(PoolEntryBuilder("minecraft:nether_wart", weight=1).add_count_function(1, 2))
loot07.add_entry(PoolEntryBuilder("minecraft:nether_sprouts", weight=1).add_count_function(1, 2))
loot07.add_entry(PoolEntryBuilder("minecraft:wither_skeleton_skull", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="07", table=loot07)

# 08-gift
loot_provider.add_loot(table_id="08-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:name_tag", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:saddle", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:cake", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:beetroot_seeds", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:hay_block", 1, 2, 3))
                       )

# 08-variety
loot08_variety = SingleLootTableBuilder()
loot08_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:lapis_lazuli", weight=6).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:jungle_sapling", weight=5).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:cocoa_beans", weight=5).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:sugar_cane", weight=4).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bamboo", weight=4).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:vine", weight=4).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:sugar", weight=3).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=3).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=3).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:paper", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:lead", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=8).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=7).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:redstone", weight=5).add_count_function(2, 5))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:acacia_sapling", weight=5).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:emerald", weight=4).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:cactus", weight=4).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=2).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=2).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:quartz", weight=5).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=4).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:twisting_vines", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:weeping_vines", weight=3).add_count_function(2, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:lava_bucket", weight=3).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:ghast_tear", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:blaze_rod", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:magma_cream", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:blaze_powder", weight=2).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:netherite_scrap", weight=1).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:nether_wart", weight=1).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:nether_sprouts", weight=1).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:wither_skeleton_skull", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:honey_bottle", weight=6).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:honeycomb", weight=5).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:beetroot_seeds", weight=4).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:beetroot_soup", weight=3).add_count_function(1, 2))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=3).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:glistering_melon_slice", weight=3).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:golden_carrot", weight=3).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=3).add_count_function(2, 4))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:fire_charge", weight=3).add_count_function(1, 3))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:cake", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:saddle", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:name_tag", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:iron_horse_armor", weight=1).add_count_function(1, 1))
loot08_variety.add_entry(PoolEntryBuilder("minecraft:leather_horse_armor", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="08-variety", table=loot08_variety)

# 08
loot08 = SingleLootTableBuilder()
loot08.add_entry(PoolEntryBuilder("minecraft:honey_bottle", weight=6).add_count_function(2, 4))
loot08.add_entry(PoolEntryBuilder("minecraft:honeycomb", weight=5).add_count_function(1, 2))
loot08.add_entry(PoolEntryBuilder("minecraft:beetroot_seeds", weight=4).add_count_function(1, 3))
loot08.add_entry(PoolEntryBuilder("minecraft:beetroot_soup", weight=3).add_count_function(1, 2))
loot08.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=3).add_count_function(2, 4))
loot08.add_entry(PoolEntryBuilder("minecraft:glistering_melon_slice", weight=3).add_count_function(1, 3))
loot08.add_entry(PoolEntryBuilder("minecraft:golden_carrot", weight=3).add_count_function(1, 3))
loot08.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=3).add_count_function(2, 4))
loot08.add_entry(PoolEntryBuilder("minecraft:fire_charge", weight=3).add_count_function(1, 3))
loot08.add_entry(PoolEntryBuilder("minecraft:cake", weight=1).add_count_function(1, 1))
loot08.add_entry(PoolEntryBuilder("minecraft:saddle", weight=1).add_count_function(1, 1))
loot08.add_entry(PoolEntryBuilder("minecraft:name_tag", weight=1).add_count_function(1, 1))
loot08.add_entry(PoolEntryBuilder("minecraft:iron_horse_armor", weight=1).add_count_function(1, 1))
loot08.add_entry(PoolEntryBuilder("minecraft:leather_horse_armor", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="08", table=loot08)

# 09-gift
loot_provider.add_loot(table_id="09-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:gunpowder", 1, 5, 7))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:phantom_membrane", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:experience_bottle", 1, 8, 10))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:lapis_lazuli", 1, 6, 8))
                       )

# 09-variety
loot09_variety = SingleLootTableBuilder()
loot09_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:lapis_lazuli", weight=6).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:jungle_sapling", weight=5).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:cocoa_beans", weight=5).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:sugar_cane", weight=4).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bamboo", weight=4).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:vine", weight=4).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:sugar", weight=3).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=3).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=3).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:paper", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:lead", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=8).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=7).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:redstone", weight=5).add_count_function(2, 5))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:acacia_sapling", weight=5).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:emerald", weight=4).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:cactus", weight=4).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=2).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=2).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:quartz", weight=5).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=4).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:twisting_vines", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:weeping_vines", weight=3).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:lava_bucket", weight=3).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:ghast_tear", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:blaze_rod", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:magma_cream", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:blaze_powder", weight=2).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:netherite_scrap", weight=1).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:nether_wart", weight=1).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:nether_sprouts", weight=1).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:wither_skeleton_skull", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:honey_bottle", weight=6).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:honeycomb", weight=5).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:beetroot_seeds", weight=4).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:beetroot_soup", weight=3).add_count_function(1, 2))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=3).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:glistering_melon_slice", weight=3).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:golden_carrot", weight=3).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=3).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:fire_charge", weight=3).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:cake", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:saddle", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:name_tag", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:iron_horse_armor", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:leather_horse_armor", weight=1).add_count_function(1, 1))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:cobweb", weight=6).add_count_function(1, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:rotten_flesh", weight=6).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=6).add_count_function(2, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=6).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:fermented_spider_eye", weight=5).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:poisonous_potato", weight=4).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:gunpowder", weight=3).add_count_function(3, 4))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:emerald", weight=2).add_count_function(2, 3))
loot09_variety.add_entry(PoolEntryBuilder("minecraft:phantom_membrane", weight=1).add_count_function(1, 2))
loot_provider.add_loot(table_id="09-variety", table=loot09_variety)

# 09
loot09 = SingleLootTableBuilder()
loot09.add_entry(PoolEntryBuilder("minecraft:cobweb", weight=6).add_count_function(1, 3))
loot09.add_entry(PoolEntryBuilder("minecraft:rotten_flesh", weight=6).add_count_function(2, 4))
loot09.add_entry(PoolEntryBuilder("minecraft:bone", weight=6).add_count_function(2, 4))
loot09.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=6).add_count_function(2, 3))
loot09.add_entry(PoolEntryBuilder("minecraft:fermented_spider_eye", weight=5).add_count_function(2, 3))
loot09.add_entry(PoolEntryBuilder("minecraft:poisonous_potato", weight=4).add_count_function(2, 3))
loot09.add_entry(PoolEntryBuilder("minecraft:gunpowder", weight=3).add_count_function(3, 4))
loot09.add_entry(PoolEntryBuilder("minecraft:emerald", weight=2).add_count_function(2, 3))
loot09.add_entry(PoolEntryBuilder("minecraft:phantom_membrane", weight=1).add_count_function(1, 2))
loot_provider.add_loot(table_id="09", table=loot09)

# 10-gift
loot_provider.add_loot(table_id="10-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:ender_eye", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:ender_pearl", 1, 3, 4))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:chorus_fruit", 1, 4, 6))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:spectral_arrow", 1, 11, 13))
                       )
# 10-variety
loot10_variety = SingleLootTableBuilder()
loot10_variety.add_entry(PoolEntryBuilder("minecraft:apple", weight=5).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:oak_sapling", weight=4).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:birch_sapling", weight=3).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:wheat_seeds", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=3).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:egg", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:pumpkin_seeds", weight=2).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:melon_seeds", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:sweet_berries", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:carrot", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:potato", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:feather", weight=6).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:spruce_sapling", weight=4).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:leather", weight=4).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:string", weight=4).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:red_mushroom", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:brown_mushroom", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=6).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:snowball", weight=5).add_count_function(3, 5))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_hide", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:dark_oak_sapling", weight=4).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:iron_ingot", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:copper_ingot", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:ice", weight=1).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:blue_ice", weight=1).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:rabbit_foot", weight=1).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_shard", weight=5).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:prismarine_crystals", weight=4).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:kelp", weight=4).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=4).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:lapis_lazuli", weight=6).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:jungle_sapling", weight=5).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:cocoa_beans", weight=5).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:sugar_cane", weight=4).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bamboo", weight=4).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:vine", weight=4).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:sugar", weight=3).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bone_meal", weight=3).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=3).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:paper", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:lead", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=8).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=7).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:coal", weight=5).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:redstone", weight=5).add_count_function(2, 5))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:acacia_sapling", weight=5).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:emerald", weight=4).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:cactus", weight=4).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=2).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=2).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:quartz", weight=5).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:gold_ingot", weight=4).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:twisting_vines", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:weeping_vines", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:lava_bucket", weight=3).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:ghast_tear", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:blaze_rod", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:magma_cream", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:blaze_powder", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:netherite_scrap", weight=1).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:nether_wart", weight=1).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:nether_sprouts", weight=1).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:wither_skeleton_skull", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:honey_bottle", weight=6).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:honeycomb", weight=5).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:beetroot_seeds", weight=4).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:beetroot_soup", weight=3).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:slime_ball", weight=3).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:glistering_melon_slice", weight=3).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:golden_carrot", weight=3).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:experience_bottle", weight=3).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:fire_charge", weight=3).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:cake", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:saddle", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:name_tag", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:iron_horse_armor", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:leather_horse_armor", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:cobweb", weight=6).add_count_function(1, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:rotten_flesh", weight=6).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=6).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:dead_bush", weight=6).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:fermented_spider_eye", weight=5).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:poisonous_potato", weight=4).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:gunpowder", weight=3).add_count_function(3, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:emerald", weight=2).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:phantom_membrane", weight=1).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:spectral_arrow", weight=7).add_count_function(3, 8))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:ender_pearl", weight=3).add_count_function(2, 3))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:chorus_fruit", weight=3).add_count_function(2, 4))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:ender_eye", weight=3).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:end_rod", weight=2).add_count_function(1, 2))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot10_variety.add_entry(PoolEntryBuilder("minecraft:dragon_breath", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="10-variety", table=loot10_variety)

# 10
loot10 = SingleLootTableBuilder()
loot10.add_entry(PoolEntryBuilder("minecraft:spectral_arrow", weight=7).add_count_function(3, 8))
loot10.add_entry(PoolEntryBuilder("minecraft:bone", weight=5).add_count_function(2, 4))
loot10.add_entry(PoolEntryBuilder("minecraft:ender_pearl", weight=3).add_count_function(2, 3))
loot10.add_entry(PoolEntryBuilder("minecraft:chorus_fruit", weight=3).add_count_function(2, 4))
loot10.add_entry(PoolEntryBuilder("minecraft:ender_eye", weight=3).add_count_function(1, 1))
loot10.add_entry(PoolEntryBuilder("minecraft:end_rod", weight=2).add_count_function(1, 2))
loot10.add_entry(PoolEntryBuilder("minecraft:diamond", weight=1).add_count_function(1, 1))
loot10.add_entry(PoolEntryBuilder("minecraft:dragon_breath", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="10", table=loot10)

# musical
lootmusical = SingleLootTableBuilder()
lootmusical.add_entry(PoolEntryBuilder("minecraft:paper", weight=1).add_count_function(2, 4))
lootmusical.add_entry(PoolEntryBuilder("minecraft:string", weight=1).add_count_function(2, 3))
lootmusical.add_entry(PoolEntryBuilder("minecraft:feather", weight=1).add_count_function(2, 3))
lootmusical.add_entry(PoolEntryBuilder("minecraft:ink_sac", weight=1).add_count_function(2, 4))
loot_provider.add_loot(table_id="musical", table=lootmusical)

# odd
lootodd = SingleLootTableBuilder()
lootodd.add_entry(PoolEntryBuilder("minecraft:bat_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:bee_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:blaze_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:cave_spider_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:cat_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:chicken_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:cod_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:cow_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:creeper_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:dolphin_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:donkey_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:drowned_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:elder_guardian_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:enderman_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:endermite_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:evoker_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:fox_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:ghast_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:guardian_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:hoglin_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:horse_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:husk_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:llama_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:magma_cube_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:mooshroom_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:mule_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:ocelot_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:panda_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:parrot_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:phantom_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:pig_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:piglin_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:polar_bear_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:pufferfish_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:rabbit_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:ravager_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:salmon_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:sheep_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:shulker_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:silverfish_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:skeleton_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:slime_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:spider_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:squid_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:stray_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:strider_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:trader_llama_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:tropical_fish_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:turtle_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:vex_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:villager_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:vindicator_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:wandering_trader_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:witch_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:wither_skeleton_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:wolf_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:zombie_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:zombie_villager_spawn_egg", weight=1).add_count_function(1, 1))
lootodd.add_entry(PoolEntryBuilder("minecraft:zombified_piglin_spawn_egg", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="odd", table=lootodd)

# rare
lootrare = SingleLootTableBuilder()
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
lootrare.add_entry(PoolEntryBuilder("minecraft:lingering_potion", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="rare", table=lootrare)

# tutorial-waterbucket
loottutorial_waterbucket = SingleLootTableBuilder()
loottutorial_waterbucket.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot_provider.add_loot(table_id="tutorial-waterbucket", table=loottutorial_waterbucket)
