from core.provider import *
from core import constant

mod_id = "oneblock"
run_list = []

aa = DataPackProvider(mod_id)
aa.get_datapack_name = (lambda: "oneblock")
run_list.append(aa)

sub_provider = PhaseProvider(mod_id)
sub_provider.get_datapack_name = (lambda: "oneblock")
run_list.append(sub_provider)

loot_provider = ModifiedLootTableProvider(mod_id)
loot_provider.get_datapack_name = (lambda: "oneblock")
run_list.append(loot_provider)

# 00
stage00 = PhaseTableBuilder(count=47, end_gift="ija-one-block:00-gift")
stage00.add_entry(PhaseEntryBuilder(constant.TYPE_BLOCK, "minecraft:grass_block").set_precedence(precedence_end=5))
stage00.add_entry(PhaseEntryBuilder(constant.TYPE_BLOCK, "minecraft:dirt").set_precedence(2, 2))
stage00.add_block("minecraft:grass_block", 19)
stage00.add_block("minecraft:oak_log", 13)
stage00.add_block("minecraft:gravel", 5)
stage00.add_mob("minecraft:pig", 1, 1)
stage00.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_00.stage_gift))
stage00.add_chest_gift(constant.GIFT_WATER_BUCKET, min_times=1, max_times=1)
sub_provider.add_phase("00", stage00)

# 01
stage01 = PhaseTableBuilder(count=240, end_gift="ija-one-block:01-gift")
stage01.add_block("minecraft:grass_block", 88)
stage01.add_block("minecraft:clay", 19)
stage01.add_block("minecraft:oak_log", 17)
stage01.add_block("minecraft:birch_log", 11)
stage01.add_block("minecraft:melon", 10)
stage01.add_block("minecraft:podzol", 9)
stage01.add_block("minecraft:pumpkin", 6)
stage01.add_mob("minecraft:chicken", 1, 1)
stage01.add_mob("minecraft:sheep", 1, 1)
stage01.add_mob("minecraft:cow", 1, 1)
stage01.add_mob("minecraft:pig", 1, 1)
stage01.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_PLAIN.stage_gift))
stage01.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_PLAIN.variety_gift))
sub_provider.add_phase("01", stage01)

# 02
stage02 = PhaseTableBuilder(count=390, end_gift="ija-one-block:02-gift")
stage02.add_block("minecraft:stone", 97)
stage02.add_block("minecraft:gravel", 37)
stage02.add_block("minecraft:dirt", 33)
stage02.add_block("minecraft:granite", 18)
stage02.add_block("minecraft:diorite", 17)
stage02.add_block("minecraft:andesite", 17)
stage02.add_block("minecraft:coal_ore", 11)
stage02.add_block("minecraft:iron_ore", 13)
stage02.add_block("minecraft:copper_ore", 17)
stage02.add_block("minecraft:oak_log", 12)
stage02.add_block("minecraft:birch_log", 9)
stage02.add_mob("minecraft:rabbit", 1, 1)
stage02.add_mob("minecraft:zombie", 2, 2)
stage02.add_mob("minecraft:spider", 2, 1)
stage02.add_mob("minecraft:creeper", 3, 1)
stage02.add_mob("minecraft:mooshroom", 1, 1)
stage02.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_UNDERGROUND.stage_gift))
stage02.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_UNDERGROUND.variety_gift))
sub_provider.add_phase("02", stage02)

# 03
stage03 = PhaseTableBuilder(count=470, end_gift="ija-one-block:03-gift")
stage03.add_block("minecraft:grass_block", 77)
stage03.add_block("minecraft:stone", 69)
stage03.add_block("minecraft:snow_block", 44)
stage03.add_block("minecraft:powder_snow", 22)
stage03.add_block("minecraft:spruce_log", 24)
stage03.add_block("minecraft:packed_ice", 17)
stage03.add_block("minecraft:andesite", 16)
stage03.add_mob("minecraft:stray", 7, 1)
stage03.add_block("minecraft:granite", 14)
stage03.add_block("minecraft:gravel", 14)
stage03.add_block("minecraft:diorite", 13)
stage03.add_block("minecraft:iron_ore", 10)
stage03.add_block("minecraft:copper_ore", 17)
stage03.add_block("minecraft:dark_oak_log", 10)
stage03.add_block("minecraft:coal_ore", 10)
stage03.add_mob("minecraft:fox", 6, 1)
stage03.add_block("minecraft:birch_log", 5)
stage03.add_block("minecraft:gold_ore", 5)
stage03.add_mob("minecraft:wolf", 3, 1)
stage03.add_mob("minecraft:polar_bear", 2, 1)
stage03.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_COLD.stage_gift))
stage03.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_COLD.variety_gift))
sub_provider.add_phase("03", stage03)

# 04
stage04 = PhaseTableBuilder(count=420, end_gift="oneblock:04-gift")
stage04.add_block("minecraft:sand", 10)
stage04.add_block("minecraft:mangrove_log", 20)
stage04.add_block("minecraft:mud", 15)
stage04.add_block("minecraft:muddy_mangrove_roots", 5)
stage04.add_block("minecraft:gravel", 8)
stage04.add_block("minecraft:clay", 5)
stage04.add_block("minecraft:iron_ore", 6)
stage04.add_block("minecraft:diorite", 3)
stage04.add_block("minecraft:stone", 4)
stage04.add_block("minecraft:coal_ore", 7)
stage04.add_block("minecraft:gold_ore", 4)
stage04.add_block("minecraft:copper_ore", 3)
stage04.add_block("minecraft:dark_oak_log", 2)
stage04.add_block("minecraft:oak_log", 6)
stage04.add_mob("minecraft:frog", 1, 1)
stage04.add_mob("minecraft:tadpole", 2, 1)
stage04.add_mob("minecraft:cod", 4, 1)
stage04.add_mob("minecraft:salmon", 4, 1)
stage04.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_SWAMP.stage_gift))
sub_provider.add_phase("04", stage04)

# 05
stage05 = PhaseTableBuilder(count=700, end_gift="ija-one-block:04-gift")
stage05.add_block("minecraft:sand", 79)
stage05.add_block("minecraft:prismarine", 77)
stage05.add_block("minecraft:prismarine_bricks", 49)
stage05.add_block("minecraft:dark_prismarine", 45)
stage05.add_block("minecraft:sea_lantern", 14)
stage05.add_block("minecraft:sponge", 13)
stage05.add_block("minecraft:iron_ore", 13)
stage05.add_block("minecraft:copper_ore", 3)
stage05.add_block("minecraft:diorite", 13)
stage05.add_block("minecraft:clay", 12)
stage05.add_block("minecraft:fire_coral_block", 12)
stage05.add_block("minecraft:coal_ore", 12)
stage05.add_block("minecraft:gold_ore", 12)
stage05.add_block("minecraft:dark_oak_log", 11)
stage05.add_block("minecraft:horn_coral_block", 11)
stage05.add_block("minecraft:stone", 10)
stage05.add_block("minecraft:tube_coral_block", 10)
stage05.add_block("minecraft:bubble_coral_block", 10)
stage05.add_block("minecraft:brain_coral_block", 10)
stage05.add_block("minecraft:oak_log", 9)
stage05.add_mob("minecraft:guardian", 6, 1)
stage05.add_mob("minecraft:cod", 4, 2)
stage05.add_mob("minecraft:tropical_fish", 4, 2)
stage05.add_mob("minecraft:salmon", 4, 2)
stage05.add_mob("minecraft:drowned", 4, 1)
stage05.add_mob("minecraft:turtle", 4, 1)
stage05.add_mob("minecraft:dolphin", 3, 1)
stage05.add_mob("minecraft:elder_guardian", 2, 2)
stage05.add_mob("minecraft:pufferfish", 2, 2)
stage05.add_mob("minecraft:squid", 2, 1)
stage05.add_block("minecraft:diamond_ore", 2)
stage05.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_OCEAN.stage_gift))
stage05.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_OCEAN.variety_gift))
stage05.add_chest_gift(constant.GIFT_MUSICAL, min_times=1, max_times=1)
sub_provider.add_phase("05", stage05)

# 06
stage06 = PhaseTableBuilder(count=570, end_gift="ija-one-block:05-gift")
stage06.add_block("minecraft:cobblestone", 212)
stage06.add_block("minecraft:mossy_cobblestone", 128)
stage06.add_block("minecraft:jungle_log", 70)
stage06.add_block("minecraft:grass_block", 41)
stage06.add_block("minecraft:redstone_ore", 17)
stage06.add_block("minecraft:iron_ore", 13)
stage06.add_block("minecraft:copper_ore", 6)
stage06.add_block("minecraft:coal_ore", 9)
stage06.add_block("minecraft:gold_ore", 8)
stage06.add_mob("minecraft:witch", 6, 1)
stage06.add_mob("minecraft:ocelot", 6, 1)
stage06.add_mob("minecraft:vex", 6, 1)
stage06.add_mob("minecraft:parrot", 2, 6)
stage06.add_mob("minecraft:horse", 4, 1)
stage06.add_block("minecraft:diamond_ore", 3)
stage06.add_mob("minecraft:panda", 2, 1)
stage06.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_FOREST.stage_gift))
stage06.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_FOREST.variety_gift))
stage06.add_chest_gift(constant.GIFT_ODD, min_times=1, max_times=1)
stage06.add_chest_gift(constant.GIFT_MUSICAL, min_times=1, max_times=1)
sub_provider.add_phase("06", stage06)

# 07
stage07 = PhaseTableBuilder(count=610, end_gift="ija-one-block:06-gift")
stage07.add_block("minecraft:red_sand", 103)
stage07.add_block("minecraft:red_sandstone", 81)
stage07.add_block("minecraft:terracotta", 40)
stage07.add_block("minecraft:sandstone", 36)
stage07.add_block("minecraft:sand", 31)
stage07.add_block("minecraft:acacia_log", 25)
stage07.add_block("minecraft:brown_terracotta", 24)
stage07.add_block("minecraft:orange_terracotta", 23)
stage07.add_block("minecraft:red_terracotta", 23)
stage07.add_block("minecraft:yellow_terracotta", 23)
stage07.add_block("minecraft:redstone_ore", 20)
stage07.add_block("minecraft:light_gray_terracotta", 17)
stage07.add_block("minecraft:white_terracotta", 17)
stage07.add_mob("minecraft:husk", 16, 2)
stage07.add_block("minecraft:emerald_ore", 13)
stage07.add_block("minecraft:iron_ore", 11)
stage07.add_block("minecraft:coal_ore", 10)
stage07.add_block("minecraft:copper_ore", 15)
stage07.add_block("minecraft:lapis_ore", 8)
stage07.add_mob("minecraft:pillager", 6, 1)
stage07.add_mob("minecraft:vindicator", 4, 1)
stage07.add_mob("minecraft:donkey", 4, 1)
stage07.add_mob("minecraft:villager", 4, 1)
stage07.add_mob("minecraft:fox", 4, 1)
stage07.add_block("minecraft:diamond_ore", 4)
stage07.add_mob("minecraft:llama", 4, 1)
stage07.add_mob("minecraft:wandering_trader", 2, 1)
stage07.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_HOT.stage_gift))
stage07.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_HOT.variety_gift))
stage07.add_chest_gift(constant.GIFT_ODD, min_times=1, max_times=1)
stage07.add_chest_gift(constant.GIFT_MUSICAL, min_times=1, max_times=1)
sub_provider.add_phase("07", stage07)

# 08
stage08 = PhaseTableBuilder(count=790, end_gift="ija-one-block:07-gift")
stage08.add_block("minecraft:netherrack", 95)
stage08.add_block("minecraft:blackstone", 80)
stage08.add_block("minecraft:soul_sand", 49)
stage08.add_block("minecraft:nether_bricks", 47)
stage08.add_block("minecraft:basalt", 37)
stage08.add_block("minecraft:red_nether_bricks", 37)
stage08.add_block("minecraft:magma_block", 31)
stage08.add_block("minecraft:warped_nylium", 30)
stage08.add_block("minecraft:crimson_nylium", 29)
stage08.add_block("minecraft:soul_soil", 21)
stage08.add_block("minecraft:glowstone", 19)
stage08.add_block("minecraft:nether_quartz_ore", 18)
stage08.add_block("minecraft:shroomlight", 17)
stage08.add_block("minecraft:nether_wart_block", 17)
stage08.add_block("minecraft:warped_wart_block", 17)
stage08.add_block("minecraft:gilded_blackstone", 16)
stage08.add_block("minecraft:nether_gold_ore", 12)
stage08.add_block("minecraft:obsidian", 12)
stage08.add_mob("minecraft:magma_cube", 9, 1)
stage08.add_mob("minecraft:blaze", 6, 1)
stage08.add_mob("minecraft:hoglin", 6, 1)
stage08.add_mob("minecraft:piglin", 6, 1)
stage08.add_mob("minecraft:ghast", 4, 1)
stage08.add_mob("minecraft:wither_skeleton", 4, 1)
stage08.add_block("minecraft:ancient_debris", 4)
stage08.add_block("minecraft:crying_obsidian", 3)
stage08.add_mob("minecraft:strider", 2, 2)
stage08.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_NETHER.stage_gift))
stage08.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_NETHER.variety_gift))
stage08.add_chest_gift(constant.GIFT_ODD, min_times=1, max_times=1)
sub_provider.add_phase("08", stage08)

# 09
stage09 = PhaseTableBuilder(count=730, end_gift="ija-one-block:08-gift")
stage09.add_block("minecraft:quartz_block", 213)
stage09.add_block("minecraft:grass_block", 69)
stage09.add_block("minecraft:oak_log", 50)
stage09.add_mob("minecraft:slime", 16, 1)
stage09.add_mob("minecraft:bee", 16, 1)
stage09.add_block("minecraft:gold_ore", 15)
stage09.add_block("minecraft:lapis_ore", 15)
stage09.add_block("minecraft:iron_ore", 13)
stage09.add_block("minecraft:copper_ore", 13)
stage09.add_block("minecraft:emerald_ore", 12)
stage09.add_block("minecraft:honeycomb_block", 10)
stage09.add_block("minecraft:redstone_ore", 8)
stage09.add_mob("minecraft:cat", 6, 1)
stage09.add_block("minecraft:diamond_ore", 6)
stage09.add_mob("minecraft:phantom", 4, 1)
stage09.add_mob("minecraft:mule", 4, 1)
stage09.add_block("minecraft:slime_block", 4)
stage09.add_block("minecraft:honey_block", 4)
stage09.add_mob("minecraft:zombie_horse", 2, 1)
stage09.add_mob("minecraft:skeleton_horse", 2, 1)
stage09.add_block("minecraft:bee_nest", 1)
stage09.add_block("minecraft:beehive", 1)
stage09.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_VILLAGE.stage_gift))
stage09.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_VILLAGE.variety_gift))
stage09.add_chest_gift(constant.GIFT_RARE, min_times=1, max_times=1)
sub_provider.add_phase("09", stage09)

# 10
stage10 = PhaseTableBuilder(count=750, end_gift="oneblock:10-gift")
stage10.add_block("minecraft:dripstone_block", 80)
stage10.add_block("minecraft:grass_block", 50)
stage10.add_block("minecraft:coarse_dirt", 20)
stage10.add_mob("minecraft:allay", 2, 1)
stage10.add_mob("minecraft:camel", 5, 1)
stage10.add_block("minecraft:cherry_log", 29)
stage10.add_block("minecraft:lapis_ore", 15)
stage10.add_block("minecraft:iron_ore", 13)
stage10.add_block("minecraft:emerald_ore", 12)
stage10.add_block("minecraft:copper_ore", 13)
stage10.add_block("minecraft:moss_block", 16)
stage10.add_block("minecraft:rooted_dirt", 8)
stage10.add_block("minecraft:oak_log", 6)
stage10.add_mob("minecraft:goat", 3, 1)
stage10.add_mob("minecraft:axolotl", 2, 2)
stage10.add_block("minecraft:stone", 8)
stage10.add_entry(
    PhaseEntryBuilder(constant.TYPE_ARCHAEOLOGY, "minecraft:suspicious_sand", 8).set_loot_table(
        "minecraft:archaeology/desert_pyramid"))
stage10.add_entry(
    PhaseEntryBuilder(constant.TYPE_ARCHAEOLOGY, "minecraft:suspicious_sand", 7).set_loot_table(
        "minecraft:archaeology/desert_well"))
stage10.add_entry(
    PhaseEntryBuilder(constant.TYPE_ARCHAEOLOGY, "minecraft:suspicious_sand", 6).set_loot_table(
        "minecraft:archaeology/ocean_ruin_warm"))
stage10.add_entry(
    PhaseEntryBuilder(constant.TYPE_ARCHAEOLOGY, "minecraft:suspicious_gravel", 8).set_loot_table(
        "minecraft:archaeology/ocean_ruin_cold"))
stage10.add_entry(
    PhaseEntryBuilder(constant.TYPE_ARCHAEOLOGY, "minecraft:suspicious_gravel", 12).set_loot_table(
        "minecraft:archaeology/trail_ruins_common"))
stage10.add_entry(
    PhaseEntryBuilder(constant.TYPE_ARCHAEOLOGY, "minecraft:suspicious_gravel", 3).set_loot_table(
        "minecraft:archaeology/trail_ruins_rare"))
stage10.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_TRAVEL.stage_gift))
stage10.add_chest_gift(constant.GIFT_RARE, min_times=1, max_times=1)
stage10.add_chest_gift(constant.GIFT_MUSICAL, min_times=1, max_times=1)
sub_provider.add_phase("10", stage10)

# 11
stage11 = PhaseTableBuilder(count=780, end_gift="ija-one-block:09-gift")
stage11.add_block("minecraft:stone_bricks", 139)
stage11.add_block("minecraft:mossy_stone_bricks", 112)
stage11.add_block("minecraft:mycelium", 84)
stage11.add_block("minecraft:cracked_stone_bricks", 59)
stage11.add_block("minecraft:chiseled_stone_bricks", 59)
stage11.add_block("minecraft:light_gray_concrete_powder", 58)
stage11.add_block("minecraft:gravel", 39)
stage11.add_block("minecraft:coal_ore", 16)
stage11.add_block("minecraft:iron_ore", 15)
stage11.add_block("minecraft:copper_ore", 8)
stage11.add_mob("minecraft:skeleton", 14, 1)
stage11.add_block("minecraft:dark_oak_log", 14)
stage11.add_block("minecraft:bone_block", 13)
stage11.add_mob("minecraft:cave_spider", 12, 1)
stage11.add_mob("minecraft:silverfish", 12, 1)
stage11.add_block("minecraft:redstone_ore", 12)
stage11.add_block("minecraft:emerald_ore", 5)
stage11.add_block("minecraft:lapis_ore", 5)
stage11.add_block("minecraft:diamond_ore", 5)
stage11.add_mob("minecraft:evoker", 4, 1)
stage11.add_mob("minecraft:creeper", 4, 1)
stage11.add_block("minecraft:jack_o_lantern", 3)
stage11.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_ISOLATED.stage_gift))
stage11.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(
        constant.STAGE_ISOLATED.variety_gift))
stage11.add_chest_gift(constant.GIFT_RARE, min_times=1, max_times=1)
stage11.add_chest_gift(constant.GIFT_ODD, min_times=1, max_times=1)
sub_provider.add_phase("11", stage11)

# 12
stage12 = PhaseTableBuilder(count=750, end_gift="oneblock:12-gift")
stage12.add_block("minecraft:deepslate", 150)
stage12.add_block("minecraft:cobbled_deepslate", 69)
stage12.add_block("minecraft:tuff", 20)
stage12.add_block("minecraft:oak_log", 3)
stage12.add_block("minecraft:reinforced_deepslate", 5)
stage12.add_block("minecraft:sculk_catalyst", 7)
stage12.add_block("minecraft:sculk", 20)
stage12.add_block("minecraft:budding_amethyst", 6)
stage12.add_block("minecraft:amethyst_block", 10)
stage12.add_block("minecraft:smooth_basalt", 12)
stage12.add_block("minecraft:calcite", 10)
stage12.add_mob("minecraft:zombie", 2, 3)
stage12.add_mob("minecraft:skeleton", 2, 1)
stage12.add_block("minecraft:deepslate_gold_ore", 15)
stage12.add_block("minecraft:deepslate_lapis_ore", 15)
stage12.add_block("minecraft:deepslate_iron_ore", 13)
stage12.add_block("minecraft:deepslate_emerald_ore", 12)
stage12.add_block("minecraft:deepslate_copper_ore", 3)
stage12.add_block("minecraft:deepslate_redstone_ore", 8)
stage12.add_mob("minecraft:creeper", 2, 1)
stage12.add_block("minecraft:deepslate_diamond_ore", 6)
stage12.add_mob("minecraft:spider", 2, 1)
stage12.add_mob("minecraft:glow_squid", 3, 1)
stage12.add_mob("minecraft:warden", 1, 1)
stage12.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_DEPTH.stage_gift))
stage12.add_chest_gift(constant.GIFT_RARE, min_times=1, max_times=1)
stage12.add_chest_gift(constant.GIFT_MUSICAL, min_times=1, max_times=1)
sub_provider.add_phase("12", stage12)

# 13
stage13 = PhaseTableBuilder(count=850, end_gift="ija-one-block:10-gift")
stage13.add_entry(PhaseEntryBuilder(type_c=constant.TYPE_TEMPLATE, id_c="oneblock:end_portal")
.set_precedence(1, 1)
.set_offset(-4, -2, -2)
.add_preprocessing(PhaseEntryBuilder(type_c=constant.TYPE_BLOCK, id_c="minecraft:end_stone"))
.add_preprocessing(
    PhaseEntryBuilder(type_c=constant.TYPE_SOUND, id_c="minecraft:block.end_portal.spawn"))
)
stage13.add_block("minecraft:end_stone", 219)
stage13.add_block("minecraft:end_stone_bricks", 160)
stage13.add_block("minecraft:purpur_block", 124)
stage13.add_block("minecraft:purpur_pillar", 115)
stage13.add_mob("minecraft:endermite", 57, 2)
stage13.add_mob("minecraft:enderman", 18, 1)
stage13.add_block("minecraft:iron_ore", 15)
stage13.add_block("minecraft:coal_ore", 15)
stage13.add_block("minecraft:gold_ore", 12)
stage13.add_block("minecraft:obsidian", 11)
stage13.add_block("minecraft:redstone_ore", 8)
stage13.add_block("minecraft:diamond_ore", 6)
stage13.add_block("minecraft:lapis_ore", 5)
stage13.add_block("minecraft:emerald_ore", 3)
stage13.add_mob("minecraft:shulker", 2, 2)
stage13.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_END.stage_gift))
stage13.add_entry(
    PhaseEntryBuilder(constant.TYPE_GIFT, "minecraft:chest", weight=2).set_loot_table(constant.STAGE_END.variety_gift))
stage13.add_chest_gift(constant.GIFT_RARE, min_times=1, max_times=1)
stage13.add_chest_gift(constant.GIFT_ODD, min_times=1, max_times=1)
stage13.add_chest_gift(constant.GIFT_MUSICAL, min_times=1, max_times=1)
sub_provider.add_phase("13", stage13)

# all
stageall = PhaseTableBuilder(count=-1)
stage13.add_entry(PhaseEntryBuilder(type_c=constant.TYPE_BLOCK, id_c="minecraft:grass_block")
.add_preprocessing(
    PhaseEntryBuilder(type_c=constant.TYPE_SOUND, id_c="minecraft:music.overworld.cherry_grove")))
stageall.add_block("minecraft:grass_block", 294)
stageall.add_block("minecraft:end_stone", 219)
stageall.add_block("minecraft:quartz_block", 213)
stageall.add_block("minecraft:cobblestone", 212)
stageall.add_block("minecraft:stone", 176)
stageall.add_block("minecraft:end_stone_bricks", 160)
stageall.add_block("minecraft:stone_bricks", 139)
stageall.add_block("minecraft:mossy_cobblestone", 128)
stageall.add_block("minecraft:purpur_block", 124)
stageall.add_block("minecraft:purpur_pillar", 115)
stageall.add_block("minecraft:mossy_stone_bricks", 112)
stageall.add_block("minecraft:sand", 110)
stageall.add_block("minecraft:red_sand", 103)
stageall.add_block("minecraft:iron_ore", 103)
stageall.add_block("minecraft:oak_log", 101)
stageall.add_block("minecraft:netherrack", 95)
stageall.add_block("minecraft:gravel", 95)
stageall.add_block("minecraft:coal_ore", 89)
stageall.add_block("minecraft:mycelium", 84)
stageall.add_block("minecraft:red_sandstone", 81)
stageall.add_block("minecraft:blackstone", 80)
stageall.add_block("minecraft:prismarine", 77)
stageall.add_block("minecraft:jungle_log", 70)
stageall.add_block("minecraft:redstone_ore", 65)
stageall.add_block("minecraft:cracked_stone_bricks", 59)
stageall.add_block("minecraft:chiseled_stone_bricks", 59)
stageall.add_block("minecraft:light_gray_concrete_powder", 58)
stageall.add_mob("minecraft:endermite", 57, 1)
stageall.add_block("minecraft:gold_ore", 52)
stageall.add_block("minecraft:soul_sand", 49)
stageall.add_block("minecraft:prismarine_bricks", 49)
stageall.add_block("minecraft:nether_bricks", 47)
stageall.add_block("minecraft:dark_prismarine", 45)
stageall.add_block("minecraft:snow_block", 44)
stageall.add_block("minecraft:diorite", 43)
stageall.add_block("minecraft:terracotta", 40)
stageall.add_block("minecraft:basalt", 37)
stageall.add_block("minecraft:red_nether_bricks", 37)
stageall.add_block("minecraft:sandstone", 36)
stageall.add_block("minecraft:dark_oak_log", 35)
stageall.add_block("minecraft:emerald_ore", 33)
stageall.add_block("minecraft:lapis_ore", 33)
stageall.add_block("minecraft:dirt", 33)
stageall.add_block("minecraft:andesite", 33)
stageall.add_block("minecraft:granite", 32)
stageall.add_block("minecraft:magma_block", 31)
stageall.add_block("minecraft:clay", 31)
stageall.add_block("minecraft:warped_nylium", 30)
stageall.add_block("minecraft:crimson_nylium", 29)
stageall.add_block("minecraft:diamond_ore", 26)
stageall.add_block("minecraft:acacia_log", 25)
stageall.add_block("minecraft:birch_log", 25)
stageall.add_block("minecraft:brown_terracotta", 24)
stageall.add_block("minecraft:spruce_log", 24)
stageall.add_block("minecraft:obsidian", 23)
stageall.add_block("minecraft:orange_terracotta", 23)
stageall.add_block("minecraft:red_terracotta", 23)
stageall.add_block("minecraft:yellow_terracotta", 23)
stageall.add_block("minecraft:soul_soil", 21)
stageall.add_block("minecraft:glowstone", 19)
stageall.add_mob("minecraft:enderman", 18, 1)
stageall.add_block("minecraft:nether_quartz_ore", 18)
stageall.add_block("minecraft:shroomlight", 17)
stageall.add_block("minecraft:nether_wart_block", 17)
stageall.add_block("minecraft:warped_wart_block", 17)
stageall.add_block("minecraft:light_gray_terracotta", 17)
stageall.add_block("minecraft:white_terracotta", 17)
stageall.add_block("minecraft:packed_ice", 17)
stageall.add_mob("minecraft:slime", 16, 1)
stageall.add_mob("minecraft:bee", 16, 1)
stageall.add_block("minecraft:gilded_blackstone", 16)
stageall.add_mob("minecraft:husk", 16, 1)
stageall.add_mob("minecraft:skeleton", 15, 1)
stageall.add_block("minecraft:sea_lantern", 14)
stageall.add_mob("minecraft:stray", 14, 1)
stageall.add_block("minecraft:bone_block", 13)
stageall.add_block("minecraft:sponge", 13)
stageall.add_mob("minecraft:cave_spider", 12, 1)
stageall.add_mob("minecraft:silverfish", 12, 1)
stageall.add_block("minecraft:nether_gold_ore", 12)
stageall.add_block("minecraft:fire_coral_block", 12)
stageall.add_block("minecraft:horn_coral_block", 11)
stageall.add_block("minecraft:honeycomb_block", 10)
stageall.add_block("minecraft:tube_coral_block", 10)
stageall.add_block("minecraft:bubble_coral_block", 10)
stageall.add_block("minecraft:brain_coral_block", 10)
stageall.add_mob("minecraft:fox", 10, 1)
stageall.add_block("minecraft:melon", 10)
stageall.add_mob("minecraft:magma_cube", 9, 1)
stageall.add_block("minecraft:podzol", 9)
stageall.add_mob("minecraft:rabbit", 8, 1)
stageall.add_mob("minecraft:cat", 6, 1)
stageall.add_mob("minecraft:blaze", 6, 1)
stageall.add_mob("minecraft:hoglin", 6, 1)
stageall.add_mob("minecraft:piglin", 6, 1)
stageall.add_mob("minecraft:pillager", 6, 1)
stageall.add_mob("minecraft:witch", 6, 1)
stageall.add_mob("minecraft:ocelot", 6, 1)
stageall.add_mob("minecraft:vex", 6, 1)
stageall.add_mob("minecraft:parrot", 6, 1)
stageall.add_mob("minecraft:guardian", 6, 1)
stageall.add_mob("minecraft:creeper", 6, 1)
stageall.add_mob("minecraft:zombie", 6, 1)
stageall.add_block("minecraft:pumpkin", 6)
stageall.add_mob("minecraft:evoker", 4, 1)
stageall.add_mob("minecraft:phantom", 4, 1)
stageall.add_mob("minecraft:mule", 4, 1)
stageall.add_block("minecraft:slime_block", 4)
stageall.add_block("minecraft:honey_block", 4)
stageall.add_mob("minecraft:ghast", 4, 1)
stageall.add_mob("minecraft:wither_skeleton", 4, 1)
stageall.add_block("minecraft:ancient_debris", 4)
stageall.add_mob("minecraft:vindicator", 4, 1)
stageall.add_mob("minecraft:donkey", 4, 1)
stageall.add_mob("minecraft:villager", 4, 1)
stageall.add_mob("minecraft:llama", 4, 1)
stageall.add_mob("minecraft:horse", 4, 1)
stageall.add_mob("minecraft:cod", 4, 1)
stageall.add_mob("minecraft:tropical_fish", 4, 1)
stageall.add_mob("minecraft:salmon", 4, 1)
stageall.add_mob("minecraft:drowned", 4, 1)
stageall.add_mob("minecraft:turtle", 4, 1)
stageall.add_mob("minecraft:spider", 4, 1)
stageall.add_mob("minecraft:chicken", 4, 1)
stageall.add_block("minecraft:jack_o_lantern", 3)
stageall.add_block("minecraft:crying_obsidian", 3)
stageall.add_mob("minecraft:wolf", 3, 1)
stageall.add_mob("minecraft:pig", 3, 1)
stageall.add_mob("minecraft:shulker", 2, 1)
stageall.add_mob("minecraft:strider", 2, 1)
stageall.add_mob("minecraft:wandering_trader", 2, 1)
stageall.add_mob("minecraft:dolphin", 2, 1)
stageall.add_mob("minecraft:elder_guardian", 2, 1)
stageall.add_mob("minecraft:pufferfish", 2, 1)
stageall.add_mob("minecraft:squid", 2, 1)
stageall.add_mob("minecraft:mooshroom", 2, 1)
stageall.add_mob("minecraft:sheep", 2, 1)
stageall.add_mob("minecraft:cow", 2, 1)
stageall.add_mob("minecraft:zombie_horse", 2, 1)
stageall.add_block("minecraft:bee_nest", 1)
stageall.add_block("minecraft:beehive", 1)
stageall.add_mob("minecraft:panda", 2, 1)
stageall.add_mob("minecraft:polar_bear", 2, 1)
sub_provider.add_phase("all", stageall)

# 04-gift
loot_provider.add_loot(table_id="04-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:tadpole_bucket", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:clay", 1, 2, 4))
                       )

# 04
loot04 = SingleLootTableBuilder()
loot04.add_entry(PoolEntryBuilder("minecraft:mangrove_propagule", weight=5).add_count_function(2, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:tadpole_bucket", weight=3).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:cod", weight=4).add_count_function(2, 4))
loot04.add_entry(PoolEntryBuilder("minecraft:salmon", weight=4).add_count_function(2, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:lily_pad", weight=3).add_count_function(2, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:seagrass", weight=3).add_count_function(2, 4))
loot04.add_entry(PoolEntryBuilder("minecraft:sea_pickle", weight=3).add_count_function(2, 4))
loot04.add_entry(PoolEntryBuilder("minecraft:dried_kelp", weight=2).add_count_function(1, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:scute", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:tube_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:bubble_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:horn_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:tube_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:bubble_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:fire_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:fire_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:horn_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:brain_coral", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:brain_coral_fan", weight=2).add_count_function(1, 2))
loot04.add_entry(PoolEntryBuilder("minecraft:nautilus_shell", weight=1).add_count_function(2, 3))
loot04.add_entry(PoolEntryBuilder("minecraft:heart_of_the_sea", weight=1).add_count_function(1, 1))
loot04.add_entry(PoolEntryBuilder("minecraft:trident", weight=1).add_count_function(1, 1))
loot04.add_entry(PoolEntryBuilder("minecraft:water_bucket", weight=1).add_count_function(1, 1))
loot04.add_entry(PoolEntryBuilder("minecraft:turtle_egg", weight=1).add_count_function(1, 1))
loot_provider.add_modified_loot(target=[constant.STAGE_SWAMP.stage_gift], table_id="04", table=loot04)

# 10-gift
loot_provider.add_loot(table_id="10-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:name_tag", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:cherry_sapling", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:pink_petals", 1, 1, 1))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:glow_berries", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:pointed_dripstone", 1, 2, 3))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:axolotl_bucket", 1, 1, 1))
                       )

# 10
loot10 = SingleLootTableBuilder()
loot10.add_entry(PoolEntryBuilder("minecraft:cherry_sapling", weight=6).add_count_function(2, 4))
loot10.add_entry(PoolEntryBuilder("minecraft:pink_petals", weight=5).add_count_function(1, 2))
loot10.add_entry(PoolEntryBuilder("minecraft:glow_berries", weight=4).add_count_function(1, 3))
loot10.add_entry(PoolEntryBuilder("minecraft:pointed_dripstone", weight=3).add_count_function(1, 2))
loot10.add_entry(PoolEntryBuilder("minecraft:dripstone_block", weight=1).add_count_function(1, 2))
loot10.add_entry(PoolEntryBuilder("minecraft:brush", weight=3).add_count_function(1, 3))
loot10.add_entry(PoolEntryBuilder("minecraft:decorated_pot", weight=3).add_count_function(1, 3))
loot10.add_entry(PoolEntryBuilder("minecraft:spore_blossom", weight=3).add_count_function(1, 3))
loot10.add_entry(PoolEntryBuilder("minecraft:hanging_roots", weight=3).add_count_function(1, 3))
loot_provider.add_modified_loot(target=[constant.STAGE_TRAVEL.stage_gift], table_id="10", table=loot10)

# 12-gift
loot_provider.add_loot(table_id="12-gift", table=LootTableBuilder()
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:echo_shard", 1, 4, 5))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:experience_bottle", 1, 8, 10))
                       .add_pool(
    LootPoolBuilder(CountBuilder(1, 1), CountBuilder(0, 0)).add_entry_item("minecraft:sculk_sensor", 1, 1, 1))
                       )

# 12
loot12 = SingleLootTableBuilder()
loot12.add_entry(PoolEntryBuilder("minecraft:iron_leggings", weight=3).add_count_function(1, 1))
loot12.add_entry(PoolEntryBuilder("minecraft:saddle", weight=3).add_count_function(1, 1))
loot12.add_entry(PoolEntryBuilder("minecraft:bone", weight=6).add_count_function(2, 4))
loot12.add_entry(PoolEntryBuilder("minecraft:book", weight=6).add_count_function(2, 3))
loot12.add_entry(PoolEntryBuilder("minecraft:leather", weight=5).add_count_function(2, 3))
loot12.add_entry(PoolEntryBuilder("minecraft:echo_shard", weight=1).add_count_function(1, 2))
loot12.add_entry(PoolEntryBuilder("minecraft:gunpowder", weight=3).add_count_function(1, 2))
loot12.add_entry(PoolEntryBuilder("minecraft:emerald", weight=4).add_count_function(2, 3))
loot12.add_entry(PoolEntryBuilder("minecraft:string", weight=1).add_count_function(1, 2))
loot_provider.add_modified_loot(target=[constant.STAGE_DEPTH.stage_gift], table_id="12", table=loot12)
